### ISSUE TITLE
Der interne Bereich für Fachschaftler ist verschwunden 

### ISSUE THREAD

**Issue by l-althueser** [fsphys-muenster/homepage-php#1]
Unter dem Link ist nichts mehr: [https://www.uni-muenster.de/Physik.FSPHYS/intern/intern-fs/](https://www.uni-muenster.de/Physik.FSPHYS/intern/intern-fs/)

**Comment by Socob** [comment]
Richtig, der ist jetzt unter https://www.uni-muenster.de/Physik.FSPHYS/intern/fs/. Hätte nicht damit gerechnet, dass da jemand Lesezeichen drauf gesetzt hat und hab deswegen kein [Redirect](https://github.com/fsphys-muenster/homepage-php/blob/master/www/data/Physik.FSPHYS/imperialive/Physik.FSPHYS/.htaccess) gemacht. Soll ich das ändern?

**Comment by l-althueser** [comment]
Ich hab da kein Lesezeichen drauf sondern über die Website navigiert ;)

**Comment by l-althueser** [comment]
![20170108](https://cloud.githubusercontent.com/assets/13698969/21751348/04472cc2-d5c6-11e6-8e5c-61fea974fd15.png)

**Comment by Socob** [comment]
Öh, über die normale Navigation oben? Eigentlich ist es da auch schon lange (automatisch) mit-geändert, evtl. mal Browser-Cache leeren?

**Comment by l-althueser** [comment]
Auch mit geleertem Cache ist der Link im Bild da der falsche ;)

**Comment by Socob** [comment]
Oh, ja, den muss ich wohl noch manuell ändern – kommt sofort!
